spring:
  application:
    name: discordQuizBot

discord:
  bot:
    token: ${DISCORD_BOT_QUIZZY}

questions:
  files:
    anatomy:
      - anatomy/skeletal/bones.json
      - anatomy/skeletal/joints.json
      - anatomy/skeletal/cartilage.json
      - anatomy/muscular/functions.json
      - anatomy/muscular/movements.json
      - anatomy/muscular/muscle_types.json
    java:
    - java/arrays.json
    - java/classesAndObjects.json
    - java/interfacesAndAbstractClasses.json
    - java/springBootCore.json
    - java/strings.json
    - java/accessModifiers.json
    - java/developmentEnvironment.json
    - java/exceptions.json
    - java/functionalInterfacesLambdas.json
    - java/io.json
    - java/springBootCore.json
    human_memory: human_memory.json
    big_five: big_five.json
    art_history: art_history.json
    python: python.json
    painting_techniques: painting_techniques.json
    programming:
    - general_programming/oop.json
    - general_programming/concurrency.json
    - general_programming/designPatterns.json
    philosophy:
    - philosophy/absurdism.json
    - philosophy/determinism.json
    - philosophy/empiricism.json
    - philosophy/existentialism.json
    - philosophy/idealism.json
    - philosophy/materialism.json
    - philosophy/naturalism.json
    - philosophy/nihilism.json
    - philosophy/rationalism.json
    - philosophy/relativism.json
    - philosophy/stoicism.json
    design_patterns:
    - design_patterns/abstractFactory.json
    - design_patterns/adapter.json
    - design_patterns/bridge.json
    - design_patterns/builder.json
    - design_patterns/chain_of_responsibility.json
    - design_patterns/command.json
    - design_patterns/composite.json
    - design_patterns/decorator.json
    - design_patterns/facade.json
    - design_patterns/factoryMethod.json
    - design_patterns/flyweight.json
    - design_patterns/interpreter.json
    - design_patterns/iterator.json
    - design_patterns/mediator.json
    - design_patterns/memento.json
    - design_patterns/object_pool.json
    - design_patterns/observer.json
    - design_patterns/prototype.json
    - design_patterns/proxy.json
    - design_patterns/singleton.json
    - design_patterns/state.json
    - design_patterns/strategy.json
    - design_patterns/template.json

  #mode - 'standard' or 'testing' or 'testing2' or 'eureka'
mode: standard