spring:
  application:
    name: discordQuizBot

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}

questions:
  files:
    java:
    - src/main/resources/java_arrays.json
    - src/main/resources/java_classesAndObjects.json
    - src/main/resources/java_interfacesAndAbstractClasses.json
    human_memory: src/main/resources/human_memory.json
    big-five: src/main/resources/big-five.json
    art_history: src/main/resources/art_history.json
    python: src/main/resources/python.json
    painting_techniques: src/main/resources/painting_techniques.json
    nihilism: src/main/resources/nihilism.json
    programming:
    - src/main/resources/programming_oop.json
    - src/main/resources/programming_concurrency.json


#mode - 'standard' or 'testing' or 'testing2' or 'eureka'
mode: testing