spring:
  application:
    name: discordQuizBot

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}

questions:
  files:
    java:
    - src/main/resources/java/arrays.json
    - src/main/resources/java/classesAndObjects.json
    - src/main/resources/java/interfacesAndAbstractClasses.json
    - src/main/resources/java/springBootCore.json
    - src/main/resources/java/strings.json
    - src/main/resources/java/accessModifiers.json
    - src/main/resources/java/developmentEnvironment.json
    - src/main/resources/java/exceptions.json
    - src/main/resources/java/functionalInterfacesLambdas.json
    - src/main/resources/java/io.json
    - src/main/resources/java/springBootCore.json
    human_memory: src/main/resources/human_memory.json
    big-five: src/main/resources/big-five.json
    art_history: src/main/resources/art_history.json
    python: src/main/resources/python.json
    painting_techniques: src/main/resources/painting_techniques.json
    nihilism: src/main/resources/nihilism.json
    programming:
    - src/main/resources/general_programming/oop.json
    - src/main/resources/general_programming/concurrency.json
    - src/main/resources/general_programming/designPatterns.json
    philosophy:
    - src/main/resources/philosophy/absurdism.json
    - src/main/resources/philosophy/determinism.json
    - src/main/resources/philosophy/empiricism.json
    - src/main/resources/philosophy/existentialism.json
    - src/main/resources/philosophy/idealism.json
    - src/main/resources/philosophy/materialism.json
    - src/main/resources/philosophy/naturalism.json
    - src/main/resources/philosophy/nihilism.json
    - src/main/resources/philosophy/rationalism.json
    - src/main/resources/philosophy/relativism.json
    - src/main/resources/philosophy/stoicism.json
    wealth_inequality: src/main/resources/wealth_inequality.json
    modern_democracy: src/main/resources/modern_democracy.json
    design_patterns:
    - src/main/resources/design_patterns/flyweight.json
    - src/main/resources/design_patterns/mediator.json
    - src/main/resources/design_patterns/template.json
    - src/main/resources/design_patterns/factoryMethod.json
    - src/main/resources/design_patterns/abstractFactory.json
    - src/main/resources/design_patterns/adapter.json
    - src/main/resources/design_patterns/decorator.json
    - src/main/resources/design_patterns/prototype.json
    - src/main/resources/design_patterns/observer.json
    - src/main/resources/design_patterns/builder.json
    #- src/main/resources/design_patterns/prototype.json
#mode - 'standard' or 'testing' or 'testing2' or 'eureka'
mode: standard