spring:
  application:
    name: discordQuizBot

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}

questions:
  files:
    java:
    - src/main/resources/java_arrays.json
    - src/main/resources/java_classesAndObjects.json
    - src/main/resources/java_interfacesAndAbstractClasses.json
    - src/main/resources/java_springBootCore.json
    - src/main/resources/java_strings.json
    - src/main/resources/java_accessModifiers.json
    - src/main/resources/java_developmentEnvironment.json
    - src/main/resources/java_exceptions.json
    - src/main/resources/java_functionalInterfacesLambdas.json
    - src/main/resources/java_io.json
    - src/main/resources/java_springBootCore.json
    spring_boot:
    - src/main/resources/java_springBootCore.json
    human_memory: src/main/resources/human_memory.json
    big-five: src/main/resources/big-five.json
    art_history: src/main/resources/art_history.json
    python: src/main/resources/python.json
    painting_techniques: src/main/resources/painting_techniques.json
    nihilism: src/main/resources/nihilism.json
    programming:
    - src/main/resources/programming_oop.json
    - src/main/resources/programming_concurrency.json
    - src/main/resources/programming_designPatterns.json
    philosophy:
    - src/main/resources/philosophy/absurdism.json
    - src/main/resources/philosophy/determinism.json
    - src/main/resources/philosophy/empiricism.json
    - src/main/resources/philosophy/existentialism.json
    - src/main/resources/philosophy/idealism.json
    - src/main/resources/philosophy/materialism.json
    - src/main/resources/philosophy/naturalism.json
    - src/main/resources/philosophy/nihilism.json
    - src/main/resources/philosophy/rationalism.json
    - src/main/resources/philosophy/relativism.json
    - src/main/resources/philosophy/stoicism.json
    wealth_inequality: src/main/resources/wealth_inequality.json
    modern_democracy: src/main/resources/modern_democracy.json

#mode - 'standard' or 'testing' or 'testing2' or 'eureka'
mode: standard