spring:
  application:
    name: discordQuizBot

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}

questions:
  files:
    java: src/main/resources/java.json
    memory: src/main/resources/memory.json
    personality: src/main/resources/personality.json
    art_history: src/main/resources/art_history.json
    python: src/main/resources/python.json
    painting_techniques: src/main/resources/painting_techniques.json
    nihilism: src/main/resources/nihilism.json

#mode - 'standard' or 'testing' or 'testing2' or 'eureka'
mode: eureka