spring:
  application:
    name: discordQuizBot

discord:
  bot:
    token: ${DISCORD_BOT_QUIZZY}


questions:
  available-topics:
    programming:
      difficulty: [2, 4, 6]
    philosophy:
      difficulty: [2, 4, 6]

  #mode - 'standard' or 'testing' or 'testing2' or 'eureka'
mode: standard