spring:
  application:
    name: discordQuizBot

discord:
  bot:
    token: ${DISCORD_BOT_QUIZZY}

questions:
  available-categories:
    "[programming]": ["programming"]
    "[philosophy]": ["philosophy"]

mode: standard