spring:
  application:
    name: discordQuizBot

discord:
  bot:
    token: ${DISCORD_BOT_QUIZZY}

questions:
  files:
    programming:
    - sample/data/general_programming/oop.json
    - sample/data/general_programming/concurrency.json
    philosophy:
    - sample/data/philosophy/absurdism.json
    - sample/data/philosophy/existentialism.json

  #mode - 'standard' or 'testing' or 'testing2' or 'eureka'
mode: standard