spring:
  application:
    name: discordQuizBot

discord:
  bot:
    token: ${DISCORD_BOT_QUIZZY}


#numbers next to available topics signify available difficulty levels
questions:
  available-topics:
    programming: ["programming"]
    philosophy: ["philosophy"]

  #mode - 'standard' or 'testing' or 'testing2' or 'eureka'
mode: standard