spring:
  application:
    name: discordQuizBot

discord:
  bot:
    token: ${DISCORD_BOT_QUIZZY}

questions:
  files:
    art_history: sample/data/art_history.json
    python: sample/data/python.json
    programming:
    - sample/data/general_programming/oop.json
    - sample/data/general_programming/concurrency.json
    - sample/data/general_programming/designPatterns.json
    philosophy:
    - sample/data/philosophy/absurdism.json
    - sample/data/philosophy/determinism.json
    - sample/data/philosophy/empiricism.json
    - sample/data/philosophy/existentialism.json
    - sample/data/philosophy/idealism.json
    - sample/data/philosophy/materialism.json
    - sample/data/philosophy/naturalism.json
    - sample/data/philosophy/nihilism.json
    - sample/data/philosophy/rationalism.json
    - sample/data/philosophy/relativism.json
    - sample/data/philosophy/stoicism.json

  #mode - 'standard' or 'testing' or 'testing2' or 'eureka'
mode: standard