spring:
  application:
    name: discordQuizBot

discord:
  bot:
    token: ${DISCORD_BOT_QUIZZY}


#numbers next to available topics signify available difficulty levels
questions:
  available-topics:
    programming: [2, 4, 6]
    philosophy: [2, 4, 6]

  #mode - 'standard' or 'testing' or 'testing2' or 'eureka'
mode: standard